# Generated by Django 5.0.6 on 2024-05-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsccommittee',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='dsccommittee',
            name='last_name',
            field=models.CharField(default='Example_name', max_length=255),
            preserve_default=False,
        ),
    ]
